### PR TITLE
Quickfix to make images available for HTTPS users (with username & pw)

### PR DESCRIPTION
**Pull request by RobM83**

### CODE REVIEW

**Comment by lad1337** [comment]
i guess i should have waited a little :/

**Comment by RobM83** [comment]
Sorry, I like the plugin and stumbled upon the image problem :)

On Thu, Dec 8, 2011 at 11:57 AM, lad1337 <
reply@reply.github.com

**Comment by lad1337** [comment]
you are correct that the image have the same issue ... but let me see if i can find a solution that does not need the same routine twice .. i never liked my substring solution

**Comment by lad1337** [comment]
would you mind testing it ... i dont have it set up as https obviously 
i pushed an update 254edf9199424775c9d46c52cdf881d8f2b191a3

**Comment by RobM83** [comment]
Everything seems to work :-)

**Comment by lad1337** [comment]
nice its live in store version is 0.1.13

**Pull request closed without merging**
