### PR TITLE
Update

### PR DESCRIPTION
**Pull request by FingerlessGlov3s**
fixs poster mode

### CODE REVIEW

**Comment by FingerlessGlov3s** [comment]
how do i find out what mode it in, small , med,big? and the picture size? all i need so i can complete

**Comment by lad1337** [comment]
I thing its a class ... But i have to Check ... Of to bed now

**Comment by FingerlessGlov3s** [comment]
ok when you know what it is ill upload my final version thats works like a
dream :)

On 6 February 2014 22:52, lad1337 notifications@github.com wrote:

> I thing its a class ... But i have to Check ... Of to bed now
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/lad1337/SickBeardConnect/pull/20#issuecomment-34384125
> .

## 

Jonny

**Comment by FingerlessGlov3s** [comment]
Ready for commit and update to the extendsion

**Comment by FingerlessGlov3s** [comment]
Can you commit 19 and 20 please and update the extension on the store.
This would be great.

**Pull request merged**
